Automatic prod deploy
matter-labs/zksync-dapp-forced-exit pull request #4
Opened 2021-04-05 04:27 UTC by StanislavBreadless

2021-04-06 17:56 UTC, popzxc commented on .github/workflows/firebase-hosting-merge.yml
> +          FIREBASE_CLI_PREVIEWS: hostingchannels
(ಠ⌣ಠ)

2021-04-06 17:56 UTC, popzxc commented on nuxt.config.js
> +const pageKeywords = "zksync withdrawal, alternative withdrawal, bulk withdrawal, zkSync, Matter Labs, rollup, ZK rollup, zero confirmation, ZKP, zero-knowledge proofs," +
Why not `array.join`?

2021-04-07 05:53 UTC, popzxc approved these changes
PR contents look OK to me; however, I don't know whether it serves its purpose :)

2021-04-13 07:31 UTC, keriat requested changes
The file nuxt.config should be saved as a .ts

Also please review the changes in eslint / prettified / style it.
Update the packages and and strict typing.
All ok it can be taken either from the zkWallet (the only available PR) or from the [zksync-dApp-withdrawal](https://github.com/matter-labs/zksync-dapp-withdrawal/pulls)

Also make sure to:
- [ ] Set up tsconfig.json
- [ ] update packages and add types
- [ ] replace the favicon located inside the /src/static/icon.png
- [ ] add the sentry / gtag services especially for it
- [ ] move all configuration scss files to the assets/style/vars and add preprocessing onBuild into nuxt.config
- [ ] add newly built cli-...env... to handle dev/prod environments and publish the package
- [ ] Apply strict types to the /src/stores/ using #typed-vuex package
- [ ] add links to the products and documentation of zkSync into the READMe.md / package.json

Helpful info:
- [Typescript.nuxt.org](Typescript.nuxt.org)
- [Typed-vuex](https://typed-vuex.roe.dev)
- [complete nuxt typescript guide](https://al-un.github.io/learn-nuxt-ts/)

2021-04-13 07:31 UTC, keriat commented on nuxt.config.js
>      '@nuxtjs/style-resources',
-This package should be added to the ```buildModules```

2021-04-13 07:31 UTC, keriat commented on nuxt.config.js
>      '@nuxtjs/pwa',
This one is safe to drop

2021-04-13 07:48 UTC, StanislavBreadless commented
@keriat 

This PR is about automatic prod deployment + some small cosmetic changes. 

I propose that I do the following:

- [ ] replace the favicon located inside the /src/static/icon.png
- [ ] add links to the products and documentation of zkSync into the READMe.md / package.json
- [ ] Fix the parts that you commented about

The rest of the changes requested are very needed for the tool and the ability to maintain it in the long-term, but out-of-scope of this PR. I can create a task for them.

2021-04-15 11:28 UTC, keriat reviewed
> @keriat
> 
> This PR is about automatic prod deployment + some small cosmetic changes.
> 
> I propose that I do the following:
> 
> * [ ]  replace the favicon located inside the /src/static/icon.png
> * [ ]  add links to the products and documentation of zkSync into the READMe.md / package.json
> * [ ]  Fix the parts that you commented about
> 
> The rest of the changes requested are very needed for the tool and the ability to maintain it in the long-term, but out-of-scope of this PR. I can create a task for them.

Let's add here two more things:

* [ ] Update Nuxt (package.json, nuxt.config.ts and relevant lint-tools)
* [ ] Replace Header / Footer / Logginin with zksync-dapp-withdrawal

2021-04-15 15:14 UTC, keriat commented
> > @keriat
> 
> > 
> 
> > This PR is about automatic prod deployment + some small cosmetic changes.
> 
> > 
> 
> > I propose that I do the following:
> 
> > 
> 
> > * [ ]  replace the favicon located inside the /src/static/icon.png
> 
> > * [ ]  add links to the products and documentation of zkSync into the READMe.md / package.json
> 
> > * [ ]  Fix the parts that you commented about
> 
> > 
> 
> > The rest of the changes requested are very needed for the tool and the ability to maintain it in the long-term, but out-of-scope of this PR. I can create a task for them.
> 
> 
> 
> Let's add here two more things:
> 
> 
> 
> * [ ] Update Nuxt (package.json, nuxt.config.ts and relevant lint-tools)
> 
> * [ ] Replace Header / Footer / Logginin with zksync-dapp-withdrawal

We've decided to push this PR and postpone changes.
@StanislavBreadless Please create some task w/t the things that require further effort.

2021-04-15 15:15 UTC, keriat approved these changes

2021-04-15 15:16 UTC, merged